version: '2'
services:
  nginx:
    container_name: nginx
    restart: always
    build: nginx
    ports:
    - "80:80"
  api:
    container_name: api
    restart: always
    build: api
  static:
    container_name: static
    restart: always
    build: static
